CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS health_check (
  id SERIAL PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'ok',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO health_check (status)
VALUES ('ok')
ON CONFLICT DO NOTHING;